version: '3.7'
services:
  app:
    build:
      context: .
      target: test
    ports:
      - 5001:5001
    command: go run .
    depends_on:
      - mysql
    volumes:
      - '.:/go/src'
    env_file: 
      - ./local.env
    init: true
  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - 3306:3306