version: '3.7'
services:
  app:
    build:
      context: ./src/
      target: base
    ports:
      - '5001:5001'
    command: go run ./...
    depends_on:
      - mysql
    volumes:
      - './src:/go/src'
    env_file: 
      - ./local.env
    init: true
  
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
