// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/AngelVlc/todos/services"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/mysql"
)

// Injectors from wire.go:

func initUsersService(db *gorm.DB, config *services.ConfigurationService) services.UsersService {
	usersService := services.NewUsersService(db, config)
	return usersService
}
