// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"github.com/AngelVlc/todos/handlers"
	"github.com/AngelVlc/todos/repositories"
	"github.com/AngelVlc/todos/services"
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
	"os"
)

// Injectors from wire.go:

func InitLogMiddleware() handlers.LogMiddleware {
	logMiddleware := handlers.NewLogMiddleware()
	return logMiddleware
}

func initDefaultAuthMiddleware(db *gorm.DB) handlers.AuthMiddleware {
	jwtTokenHelper := services.NewJwtTokenHelper()
	osEnvGetter := services.NewOsEnvGetter()
	defaultConfigurationService := services.NewDefaultConfigurationService(osEnvGetter)
	defaultAuthService := services.NewDefaultAuthService(jwtTokenHelper, defaultConfigurationService)
	defaultAuthMiddleware := handlers.NewDefaultAuthMiddleware(defaultAuthService)
	return defaultAuthMiddleware
}

func initMockedAuthMiddleware() handlers.AuthMiddleware {
	mockedAuthMiddleware := handlers.NewMockedAuthMiddleware()
	return mockedAuthMiddleware
}

func InitRequireAdminMiddleware() handlers.RequireAdminMiddleware {
	defaultRequireAdminMiddleware := handlers.NewDefaultRequireAdminMiddleware()
	return defaultRequireAdminMiddleware
}

func initDefaultRequestCounterMiddleware(db *gorm.DB) handlers.RequestCounterMiddleware {
	defaultCountersService := services.NewDefaultCountersService(db)
	defaultRequestCounterMiddleware := handlers.NewDefaultRequestCounterMiddleware(defaultCountersService)
	return defaultRequestCounterMiddleware
}

func initMockedRequestCounterMiddleware() handlers.RequestCounterMiddleware {
	mockedRequestCounterMiddleware := handlers.NewMockedRequestCounterMiddleware()
	return mockedRequestCounterMiddleware
}

func initDefaultCountersService(db *gorm.DB) services.CountersService {
	defaultCountersService := services.NewDefaultCountersService(db)
	return defaultCountersService
}

func initMockedCountersService() services.CountersService {
	mockedCountersService := services.NewMockedCountersService()
	return mockedCountersService
}

func initDefaultListsService(db *gorm.DB) services.ListsService {
	defaultListsRepository := repositories.NewDefaultListsRepository(db)
	defaultListsService := services.NewDefaultListsService(db, defaultListsRepository)
	return defaultListsService
}

func initMockedListsService() services.ListsService {
	mockedListsService := services.NewMockedListsService()
	return mockedListsService
}

func initDefaultAuthService() services.AuthService {
	jwtTokenHelper := services.NewJwtTokenHelper()
	osEnvGetter := services.NewOsEnvGetter()
	defaultConfigurationService := services.NewDefaultConfigurationService(osEnvGetter)
	defaultAuthService := services.NewDefaultAuthService(jwtTokenHelper, defaultConfigurationService)
	return defaultAuthService
}

func initMockedAuthService() services.AuthService {
	mockedAuthService := services.NewMockedAuthService()
	return mockedAuthService
}

func initDefaultUsersService(db *gorm.DB) services.UsersService {
	bcryptHelper := services.NewBcryptHelper()
	defaultUsersRepository := repositories.NewDefaultUsersRepository(db)
	defaultUsersService := services.NewDefaultUsersService(bcryptHelper, defaultUsersRepository)
	return defaultUsersService
}

func initMockedUsersService() services.UsersService {
	mockedUsersService := services.NewMockedUsersService()
	return mockedUsersService
}

func initDefaultUsersRepository(db *gorm.DB) repositories.UsersRepository {
	defaultUsersRepository := repositories.NewDefaultUsersRepository(db)
	return defaultUsersRepository
}

func initMockedUsersRepository() repositories.UsersRepository {
	mockedUsersRepository := repositories.NewMockedUsersRepository()
	return mockedUsersRepository
}

func initDefaultListsRepositories(db *gorm.DB) repositories.ListsRepository {
	defaultListsRepository := repositories.NewDefaultListsRepository(db)
	return defaultListsRepository
}

func initMockedListsRepository() repositories.ListsRepository {
	mockedListsRepository := repositories.NewMockedListsRepository()
	return mockedListsRepository
}

func InitConfigurationService() services.ConfigurationService {
	osEnvGetter := services.NewOsEnvGetter()
	defaultConfigurationService := services.NewDefaultConfigurationService(osEnvGetter)
	return defaultConfigurationService
}

// wire.go:

func InitAuthMiddleware(db *gorm.DB) handlers.AuthMiddleware {
	if inTestingMode() {
		return initMockedAuthMiddleware()
	} else {
		return initDefaultAuthMiddleware(db)
	}
}

func InitRequestCounterMiddleware(db *gorm.DB) handlers.RequestCounterMiddleware {
	if inTestingMode() {
		return initMockedRequestCounterMiddleware()
	} else {
		return initDefaultRequestCounterMiddleware(db)
	}
}

func InitCountersService(db *gorm.DB) services.CountersService {
	if inTestingMode() {
		return initMockedCountersService()
	} else {
		return initDefaultCountersService(db)
	}
}

func InitListsService(db *gorm.DB) services.ListsService {
	if inTestingMode() {
		return initMockedListsService()
	} else {
		return initDefaultListsService(db)
	}
}

func InitAuthService() services.AuthService {
	if inTestingMode() {
		return initMockedAuthService()
	} else {
		return initDefaultAuthService()
	}
}

func InitUsersService(db *gorm.DB) services.UsersService {
	if inTestingMode() {
		return initMockedUsersService()
	} else {
		return initDefaultUsersService(db)
	}
}

func InitUsersRepository(db *gorm.DB) repositories.UsersRepository {
	if inTestingMode() {
		return initMockedUsersRepository()
	} else {
		return initDefaultUsersRepository(db)
	}
}

func InitListsRepository(db *gorm.DB) repositories.ListsRepository {
	if inTestingMode() {
		return initMockedListsRepository()
	} else {
		return initDefaultListsRepositories(db)
	}
}

func inTestingMode() bool {
	return len(os.Getenv("TESTING")) > 0
}

var EnvGetterSet = wire.NewSet(services.NewOsEnvGetter, wire.Bind(new(services.EnvGetter), new(*services.OsEnvGetter)))

var TokenHelperSet = wire.NewSet(services.NewJwtTokenHelper, wire.Bind(new(services.TokenHelper), new(*services.JwtTokenHelper)))

var MockedTokenHelperSet = wire.NewSet(services.NewMockedTokenHelper, wire.Bind(new(services.TokenHelper), new(*services.MockedTokenHelper)))

var CryptoHelperSet = wire.NewSet(services.NewBcryptHelper, wire.Bind(new(services.CryptoHelper), new(*services.BcryptHelper)))

var ConfigurationServiceSet = wire.NewSet(
	EnvGetterSet, services.NewDefaultConfigurationService, wire.Bind(new(services.ConfigurationService), new(*services.DefaultConfigurationService)))

var MockedConfigurationServiceSet = wire.NewSet(services.NewMockedConfigurationService, wire.Bind(new(services.ConfigurationService), new(*services.MockedConfigurationService)))

var AuthServiceSet = wire.NewSet(
	TokenHelperSet,
	ConfigurationServiceSet, services.NewDefaultAuthService, wire.Bind(new(services.AuthService), new(*services.DefaultAuthService)))

var MockedAuthServiceSet = wire.NewSet(services.NewMockedAuthService, wire.Bind(new(services.AuthService), new(*services.MockedAuthService)))

var UsersServiceSet = wire.NewSet(services.NewDefaultUsersService, wire.Bind(new(services.UsersService), new(*services.DefaultUsersService)))

var MockedUsersServiceSet = wire.NewSet(services.NewMockedUsersService, wire.Bind(new(services.UsersService), new(*services.MockedUsersService)))

var ListsServiceSet = wire.NewSet(services.NewDefaultListsService, wire.Bind(new(services.ListsService), new(*services.DefaultListsService)))

var MockedListsServiceSet = wire.NewSet(services.NewMockedListsService, wire.Bind(new(services.ListsService), new(*services.MockedListsService)))

var CountersServiceSet = wire.NewSet(services.NewDefaultCountersService, wire.Bind(new(services.CountersService), new(*services.DefaultCountersService)))

var MockedCountersServiceSet = wire.NewSet(services.NewMockedCountersService, wire.Bind(new(services.CountersService), new(*services.MockedCountersService)))

var RequestCounterMiddlewareSet = wire.NewSet(
	CountersServiceSet, handlers.NewDefaultRequestCounterMiddleware, wire.Bind(new(handlers.RequestCounterMiddleware), new(*handlers.DefaultRequestCounterMiddleware)))

var MockedRequestCounterMiddlewareSet = wire.NewSet(handlers.NewMockedRequestCounterMiddleware, wire.Bind(new(handlers.RequestCounterMiddleware), new(*handlers.MockedRequestCounterMiddleware)))

var AuthMiddlewareSet = wire.NewSet(
	AuthServiceSet, handlers.NewDefaultAuthMiddleware, wire.Bind(new(handlers.AuthMiddleware), new(*handlers.DefaultAuthMiddleware)))

var MockedAuthMiddlewareSet = wire.NewSet(handlers.NewMockedAuthMiddleware, wire.Bind(new(handlers.AuthMiddleware), new(*handlers.MockedAuthMiddleware)))

var RequireAdminMiddlewareSet = wire.NewSet(handlers.NewDefaultRequireAdminMiddleware, wire.Bind(new(handlers.RequireAdminMiddleware), new(*handlers.DefaultRequireAdminMiddleware)))

var UsersRepositorySet = wire.NewSet(repositories.NewDefaultUsersRepository, wire.Bind(new(repositories.UsersRepository), new(*repositories.DefaultUsersRepository)))

var MockedUsersRepositorySet = wire.NewSet(repositories.NewMockedUsersRepository, wire.Bind(new(repositories.UsersRepository), new(*repositories.MockedUsersRepository)))

var ListsRepositorySet = wire.NewSet(repositories.NewDefaultListsRepository, wire.Bind(new(repositories.ListsRepository), new(*repositories.DefaultListsRepository)))

var MockedListsRepositorySet = wire.NewSet(repositories.NewMockedListsRepository, wire.Bind(new(repositories.ListsRepository), new(*repositories.MockedListsRepository)))
