// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/AngelVlc/todos/providers"
	"github.com/AngelVlc/todos/services"
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitUsersService(db *gorm.DB) services.UsersService {
	usersService := services.NewUsersService(db)
	return usersService
}

func InitCountersService(db *gorm.DB) services.CountersService {
	countersService := services.NewCountersService(db)
	return countersService
}

func InitListsService(db *gorm.DB) services.ListsService {
	listsService := services.NewListsService(db)
	return listsService
}

func InitAuthService() services.AuthService {
	jwtTokenProvider := providers.NewJwtTokenProvider()
	osEnvGetter := providers.NewOsEnvGetter()
	configurationService := services.NewConfigurationService(osEnvGetter)
	authService := services.NewAuthService(jwtTokenProvider, configurationService)
	return authService
}

func InitConfigurationService() services.ConfigurationService {
	osEnvGetter := providers.NewOsEnvGetter()
	configurationService := services.NewConfigurationService(osEnvGetter)
	return configurationService
}

// wire.go:

var ConfigurationServiceSet = wire.NewSet(providers.NewOsEnvGetter, wire.Bind(new(providers.EnvGetter), new(*providers.OsEnvGetter)), services.NewConfigurationService)

var TokenProviderSet = wire.NewSet(providers.NewJwtTokenProvider, wire.Bind(new(providers.TokenProvider), new(*providers.JwtTokenProvider)))
