// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/AngelVlc/todos/providers"
	"github.com/AngelVlc/todos/services"
	"github.com/google/wire"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitUsersService(db *gorm.DB) services.UsersService {
	usersService := services.NewUsersService(db)
	return usersService
}

func InitCountersService(db *gorm.DB) services.CountersService {
	countersService := services.NewCountersService(db)
	return countersService
}

func InitListsService(db *gorm.DB) services.ListsService {
	listsService := services.NewListsService(db)
	return listsService
}

func InitJwtProvider() services.JwtProvider {
	osEnvGetter := providers.NewOsEnvGetter()
	configurationService := services.NewConfigurationService(osEnvGetter)
	jwtProvider := services.NewJwtProvider(configurationService)
	return jwtProvider
}

func InitAuthService() services.AuthService {
	osEnvGetter := providers.NewOsEnvGetter()
	configurationService := services.NewConfigurationService(osEnvGetter)
	jwtProvider := services.NewJwtProvider(configurationService)
	authService := services.NewAuthService(jwtProvider)
	return authService
}

func InitConfigurationService() services.ConfigurationService {
	osEnvGetter := providers.NewOsEnvGetter()
	configurationService := services.NewConfigurationService(osEnvGetter)
	return configurationService
}

// wire.go:

var ConfigurationServiceSet = wire.NewSet(providers.NewOsEnvGetter, wire.Bind(new(providers.EnvGetter), new(*providers.OsEnvGetter)), services.NewConfigurationService)
